name: challenge

on: push

jobs:
  job1:
    name: ubuntu print date
    runs-on: ubuntu-latest
    steps:
      - name: Pull all code from repo
        uses: actions/checkout@v2
      - name: Print Date
        run: date
  job2:
    name: windows print date
    runs-on: windows-latest
    steps:
      - name: Pull all code from repo
        uses: actions/checkout@v2
      - name: Print Date
        run: Get-Date
  job3:
    name: mac print date
    runs-on: macos-latest
    steps:
      - name: Pull all code from repo
        uses: actions/checkout@v2
      - name: Print Date
        run: date
  job4:
    name: ubuntu last to print date
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Pull all code from repo
        uses: actions/checkout@v2
      - name: Print Date
        run: date